### ISSUE TITLE
Gulp fails to import the library with babel 7 and preset-env

### ISSUE THREAD

**Issue by driss-chelouati** [mattiacoll/vanilla-marquee#3]
Doing `import marquee from 'vanilla-marquee'` fails in my project. Here is the stack trace:
```
node_modules\vanilla-marquee\dist\vanilla-marquee.js:704
export default marquee;
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
    at formatError (C:\Users\21267\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^4.0.0\format-error.js:21:10)
    at Gulp.<anonymous> (C:\Users\21267\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^4.0.0\log\events.js:33:15)
    at Gulp.emit (events.js:215:7)
    at Gulp.EventEmitter.emit (domain.js:476:20)
    at Object.error (C:\dev\envato\bulkit\bulkit-alpine\node_modules\undertaker\lib\helpers\createExtensions.js:61:10)
    at handler (C:\dev\envato\bulkit\bulkit-alpine\node_modules\now-and-later\lib\map.js:50:14)
    at f (C:\dev\envato\bulkit\bulkit-alpine\node_modules\once\once.js:25:25)
    at f (C:\dev\envato\bulkit\bulkit-alpine\node_modules\once\once.js:25:25)
    at tryCatch (C:\dev\envato\bulkit\bulkit-alpine\node_modules\async-done\index.js:24:15)
    at done (C:\dev\envato\bulkit\bulkit-alpine\node_modules\async-done\index.js:40:12)
[15:38:34] 'dev' errored after 39 s
```

**Comment by mattiacoll** [comment]
Apparently gulp doesn't support es6 modules, if you want to import them there is [this article](https://nshki.com/es6-in-gulp-projects/) which shows you how to do it.
